name: DesertBaseDefence
main: innocentius.net.cjfw.CJFWmain
version: 1.1.0
website: http://www.innocentius.net/wordpress
description: >
             CJFWmain
commands:
   cjfw:
       description: the control for the whole game
       permission: cjfw.admin
       usage: |
              /cjfw - for a hello message and this usage page
              /cjfw init - init the game, DO THIS BEFORE SETBASE
              /cjfw start - start game, MUST initialize first
              /cjfw stop - pause game, can use start to re-open the game from current process.
              /cjfw reset - reset critical parameter for re-init
              /cjfw rank - broadcast rank of current players, COULD ONLY BE USED AFTER GAME IS FINISHED
              /cjfw showhp - show current hp of base, must start game
              /cjfw showloc - show the current position of bases.
              /cjfw setdiff <difficulty> - sets the difficulty of game, 1 as default, 0 as no mobs spawned, DON'T GO BEYOND 3
              /cjfw setbase <basenumber> - set the location of three bases, basenumber must be 1 for blue or 2 for aqua or                                            3 for purple, DO THIS AFTER INIT
              /cjfw heal <basename> <playername> - heal a base 5% with sender's name, ONLY USE THIS IN COM_BLOCK
              /cjfw fortify <basename> <playername> - fortify a base for 3 sec with sender's name, ONLY USE IN COM_BLOCK       
permissions:
   cjfw.admin:
       description: op has the control of game
       default: op
